spring.application.name=bff

spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=50MB

jwt.secret.key=${JWT_SECRET_KEY:4a8a37efb83e14fdeadb0f7ec20c4e33ec018b0cee091e247a08d792d7be2f06}
jwt.access.token.expiry=${JWT_ACCESS_TOKEN_EXPIRY:86400000}
jwt.refresh.token.expiry=${JWT_REFRESH_TOKEN_EXPIRY:604800000}
core.backend.url=${CORE_BACKEND_URL:http://localhost:8080/api}

server.port=${SERVER_PORT:8081}




